site_name: Portfolio - Marcin Karmelita
site_author: Marcin Karmelita
site_description: >-
  Portfolio projektów Data Science oraz AI

theme:
  name: material
  future: false
  logo: assets/uplogo.png
  favicon: assets/uplogo.png
  palette:
    primary: brown
    accent: grey

nav: 
    - Strona Domowa: index.md
    - Projekty AI:
        - MeeetingSum: MeeetingSum/index.md
        - ScanMyDoc: ScanMyDoc/index.md
        - TurboGPT: TurboGPT/index.md
    - Projekty DS:
        - Iris: iris/index.md
        - Titanic: titanic/index.md

markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details

extra_css:
    - assets/stylesheets/extra.css